### ISSUE TITLE
`bosh cck` not needed, it fixes itself?

### ISSUE THREAD

**Issue by SamuelMarks** [mariash/learn-bosh#15]
Following http://mariash.github.io/learn-bosh/#failing_vm

And I was getting all the same output. Now I just kept `watch` on `bosh vms` rather than running `bosh cck`, and eventually it came online.

**Comment by sramji** [comment]
I found the same thing.  You have to get in there pretty quickly to beat the BOSH self-healing; if you do, you can `bosh cck` successfully.

**Comment by mariash** [comment]
@SamuelMarks good catch! I updated the section with resurrector demonstration: http://mariash.github.io/learn-bosh/#failing_vm
