### ISSUE TITLE
How to add blobs to the blobstore

### ISSUE THREAD

**Issue by 1123** [mariash/learn-bosh#23]
Great tutorial! I guess many people will use this as a starting point for more involved bosh deployments. 

I tried adding a new blob to the blob-store on bosh-lite:

* added a file blobs/foo.txt
* tried bosh upload blobs 

Got the response 

foo.txt uploading.../Library/Ruby/Gems/2.0.0/gems/blobstore_client-1.3262.4.0/lib/blobstore_client/s3_blobstore_client.rb:62:in `create_file': unsupported action (Bosh::Blobstore::BlobstoreError)

Also tried different file names, paths, file types without success. 
Any ideas?

**Comment by mariash** [comment]
check permissions on your s3 bucket, if you allowed to create files with s3 credentials you provided in config/blobs.yml. Try to use awscli directly to upload file.

**Comment by 1123** [comment]
Thanks. Good to know.
