### ISSUE TITLE
Retry: Get https://192.168.50.6:25555/info

### ISSUE THREAD

**Issue by mglina** [mariash/learn-bosh#25]
Hi :)

I hope this good place to look for help. I am taking first step with cloudfoundry. I finish almost http://mariash.github.io/learn-bosh/ and close my Linux. When I back I have big problem with 

Fetching info:
  Performing request GET 'https://192.168.50.6:25555/info':
    Performing GET request:
      Retry: Get https://192.168.50.6:25555/info: dial tcp 192.168.50.6:25555: getsockopt: network is unreachable

Exit code 1

Could someone please help mi fix that problem ? I know this adress is set on first command of that tutorial, but for such reason my admin password is not working.

**Comment by mariash** [comment]
@mglina make sure your virtualbox VM is running

**Comment by mglina** [comment]
Hi :)

This is strange think. Becasue when i  type virtualbox startvm
vm-uupp=€×£×¥=÷

It only pop up virtualbox app, when i must clik start on that vm.

Next issue is when I start this mashine i must log in.
I know where is the file with login and password. As in tutorial i loged as
admin. I know password but whrn i start vm and type password and login it
is login error.

Br.

16.06.2017 03:14 "Maria Shaldibina" <notifications@github.com> napisał(a):

**Comment by mariash** [comment]
how do you login? `bosh login` command?

**Comment by mglina** [comment]
That is ip error when I type bosh login.
By login i mean logim to vm which i started.

16.06.2017 09:07 "Maria Shaldibina" <notifications@github.com> napisał(a):

**Comment by mglina** [comment]
sorry my mistake.

root12@root12-Aspire-7551:~/Pulpit$ bosh login
Expected non-empty Director URL

Exit code 1

this in VM and error, which I talked.

[image: Obraz w treści 1]



2017-06-16 9:17 GMT+02:00 Marek Glinkowski <mglina67@gmail.com>:

**Comment by mglina** [comment]
Hi :)

Do you have any idea how to help ?

2017-06-16 9:30 GMT+02:00 Marek Glinkowski <mglina67@gmail.com>:

**Comment by mariash** [comment]
@mglina please check this resource on how to run bosh commands: http://bosh.io/docs/cli-v2.html

You can run `bosh login --help` to see the command helper.

Also, if you have questions please ask them in bosh slack channel at https://cloudfoundry.slack.com, channel name is #bosh. 

Slack is the more appropriate place to ask these questions and you'll get faster feedback there. I am going to close this issue.

**Comment by mglina** [comment]
hi :)

Are you sure the name of channel  is #bosh ? I sing in and I can't find it.

Br,
Mglina

2017-06-20 2:10 GMT+02:00 Maria Shaldibina <notifications@github.com>:

**Comment by mglina** [comment]
Nevermind I found :) Have a nice day.

2017-06-24 16:44 GMT+02:00 Marek Glinkowski <mglina67@gmail.com>:

**Comment by mariash** [comment]
yes please use the link `bosh on slack` here http://bosh.io

**Comment by mglina** [comment]
ok I found that slack :)

could you tell me more what is that error :

root12@root12-Aspire-7551:~/Pulpit/learn-bosh-release$ bosh login
Expected non-empty Director URL

Exit code 1

What is means and how to correct that ?


2017-06-24 19:13 GMT+02:00 Maria Shaldibina <notifications@github.com>:

**Comment by mariash** [comment]
You should specify the environment when you logging in. If you are following the tutorial it says you need to run `bosh -e vbox login`

**Comment by mglina** [comment]
I try that :)

Fetching info:
  Performing request GET 'https://192.168.50.6:25555/info':
    Performing GET request:
      Retry: Get https://192.168.50.6:25555/info: dial tcp
192.168.50.6:25555: getsockopt: no route to host

Exit code 1


This is IP error from me ticket.

Maybe I think wrong if yes please correct my :)
Why this VM is not started automatic ? This is problem with deploy. When it
is not change at all it do not started. Why it is like that in that
tutiroal ?

2017-06-24 19:20 GMT+02:00 Maria Shaldibina <notifications@github.com>:

**Comment by mglina** [comment]
Hi again.


I'm sorry to bother You, again. Could You please give me concat to somebody
from slack who is helpful and will be able to help me. I wrote as You
suggest on some channel name #bosh ( I thought it is right one) , but they
send me to #bosh, so I thik I can't find it correctly.

**Comment by mariash** [comment]
@mglina you were in the right place #bosh. I think the person who told you to ask in #bosh was confused.
