### ISSUE TITLE
Cannot open: No Such file or directory - deploy

### ISSUE THREAD

**Issue by fbys294** [mariash/learn-bosh#30]
I'm getting the following error when I deploy manifest.yml

16:44:09 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
16:44:09 | Preparing deployment: Preparing deployment (00:00:00)
16:44:09 | Preparing package compilation: Finding packages to compile (00:00:00)
16:44:09 | Compiling packages: ruby/62412bff15bb2d02b8095105e2acd57d80e7ec9c (00:00:08)
            L Error: Action Failed get_task: Task 5dc8b49a-f74e-46d9-673c-fe3caa2b1414 result: Compiling package ruby: Running packaging script: Command exited with 2; Stdout: , Stderr: + tar xzf ruby/ruby-2.1.4.tar.gz
tar (child): ruby/ruby-2.1.4.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

16:44:17 | Error: Action Failed get_task: Task 5dc8b49a-f74e-46d9-673c-fe3caa2b1414 result: Compiling package ruby: Running packaging script: Command exited with 2; Stdout: , Stderr: + tar xzf ruby/ruby-2.1.4.tar.gz
tar (child): ruby/ruby-2.1.4.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by mariash** [comment]
did you run `bosh create release` in  the latest learn-bosh-release (make sure to git pull latest changes)

**Comment by fbys294** [comment]
closing issue, i believe it was resolved during an update.
