### ISSUE TITLE
manifest.yml needs to have director udid updated (manually?)

### ISSUE THREAD

**Issue by danger-ranger** [mariash/learn-bosh#6]
On this step http://mariash.github.io/learn-bosh/#set_manifest

The director_uuid in the manifest.yml needed to be set to the uuid of the created director

Might be worth mentioning in the tutorial

**Comment by MattHall** [comment]
Added a PR for this here: https://github.com/mariash/learn-bosh/pull/10

**Comment by cppforlife** [comment]
Merged.
